//Comparison Operators(boolean)
var a = 10;
var b = 20;
console.log(a < b);
var c = 40;
var d = 30;
console.log(c > d);
var e = 50;
var f = 60;
console.log(e <= f);
var g = 80;
var h = 70;
console.log(g >= h);
var i = 90;
var j = 90;
console.log(i == j);
var k = 100;
var l = 110;
console.log(k != l);
var m = 120;
var n = 120;
console.log(m === n);
